package view;




import graph.Graph;
import graph.Usuario;

import java.awt.CardLayout;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import service.FacebookAccess;
import service.IFacebookAccess;
import service.IFacebookGetByAccess;

/**
 *
 * @author Macário
 */
public class UI extends javax.swing.JFrame {

    CardLayout cards;
    private IFacebookAccess acesso;
    private IFacebookGetByAccess meuAcesso;
    private List<Usuario> amigos;
    private Graph grafo;
    private String userToken;
    private List<Usuario> query;
    private DefaultTableModel model;
    
    public UI() {
        initComponents();
        cards = new CardLayout();
        painelPrincipal.setLayout(cards);
        painelPrincipal.add("inicio",painelInicio);
        painelPrincipal.add("home",painelHome);
        painelPrincipal.add("op1",painelOp1);
        painelPrincipal.add("op2",painelOp2);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        painelInicio = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelDescToken = new javax.swing.JLabel();
        fieldToken = new javax.swing.JTextField();
        buttonEntrar = new javax.swing.JButton();
        painelHome = new javax.swing.JPanel();
        labelBemVindo = new javax.swing.JLabel();
        labelDescHome = new javax.swing.JLabel();
        buttonMeusFiltros = new javax.swing.JButton();
        buttonFlirtingFiltros = new javax.swing.JButton();
        voltar1 = new javax.swing.JButton();
        painelOp1 = new javax.swing.JPanel();
        labelDescOp1 = new javax.swing.JLabel();
        checkSexo = new javax.swing.JCheckBox();
        checkIdade = new javax.swing.JCheckBox();
        checkMasc = new javax.swing.JCheckBox();
        checkFem = new javax.swing.JCheckBox();
        buttonExec = new javax.swing.JButton();
        voltar2 = new javax.swing.JButton();
        painelOp2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        voltar3 = new javax.swing.JButton();
        labelTitle = new javax.swing.JLabel();
        painelPrincipal = new javax.swing.JPanel();

        labelTitulo.setText("GetFlirting");

        labelDescToken.setText("Insira a token de acesso do Facebook");

        buttonEntrar.setText("ENTRAR");
        buttonEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelInicioLayout = new javax.swing.GroupLayout(painelInicio);
        painelInicio.setLayout(painelInicioLayout);
        painelInicioLayout.setHorizontalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInicioLayout.createSequentialGroup()
                .addGroup(painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInicioLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(fieldToken, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelInicioLayout.createSequentialGroup()
                        .addGap(247, 247, 247)
                        .addComponent(labelDescToken))
                    .addGroup(painelInicioLayout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(labelTitulo))
                    .addGroup(painelInicioLayout.createSequentialGroup()
                        .addGap(309, 309, 309)
                        .addComponent(buttonEntrar)))
                .addContainerGap(192, Short.MAX_VALUE))
        );
        painelInicioLayout.setVerticalGroup(
            painelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInicioLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(labelTitulo)
                .addGap(94, 94, 94)
                .addComponent(labelDescToken)
                .addGap(33, 33, 33)
                .addComponent(fieldToken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(buttonEntrar)
                .addGap(29, 29, 29))
        );

        labelBemVindo.setText("Bem vindo ao GetFlirting");

        labelDescHome.setText("Para encontrar a sua paquera, escolha uma das opções abaixo!");

        buttonMeusFiltros.setText("Quero escolher meus próprios filtros");
        buttonMeusFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMeusFiltrosActionPerformed(evt);
            }
        });

        buttonFlirtingFiltros.setText("Quero que o GetFlirting escolha por mim");
        buttonFlirtingFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFlirtingFiltrosActionPerformed(evt);
            }
        });

        voltar1.setText("Voltar");
        voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelHomeLayout = new javax.swing.GroupLayout(painelHome);
        painelHome.setLayout(painelHomeLayout);
        painelHomeLayout.setHorizontalGroup(
            painelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHomeLayout.createSequentialGroup()
                .addGroup(painelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelHomeLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(labelBemVindo))
                    .addGroup(painelHomeLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(painelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDescHome)
                            .addGroup(painelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonMeusFiltros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonFlirtingFiltros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(painelHomeLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(voltar1)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        painelHomeLayout.setVerticalGroup(
            painelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelHomeLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(labelBemVindo)
                .addGap(73, 73, 73)
                .addComponent(labelDescHome)
                .addGap(39, 39, 39)
                .addComponent(buttonMeusFiltros)
                .addGap(18, 18, 18)
                .addComponent(buttonFlirtingFiltros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(voltar1)
                .addContainerGap())
        );

        labelDescOp1.setText("Escolha entre os filtros abaixo");

        checkSexo.setText("Sexo");

        checkIdade.setText("Idade");

        checkMasc.setText("Masculino");

        checkFem.setText("Feminino");

        buttonExec.setText("GetFlirting");
        buttonExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
					buttonExecActionPerformed(evt);
				} catch (MalformedURLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        });

        voltar2.setText("Voltar");
        voltar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelOp1Layout = new javax.swing.GroupLayout(painelOp1);
        painelOp1.setLayout(painelOp1Layout);
        painelOp1Layout.setHorizontalGroup(
            painelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOp1Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(painelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkIdade)
                    .addComponent(labelDescOp1)
                    .addGroup(painelOp1Layout.createSequentialGroup()
                        .addGroup(painelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelOp1Layout.createSequentialGroup()
                                .addComponent(checkSexo)
                                .addGap(18, 18, 18)
                                .addComponent(checkMasc))
                            .addComponent(buttonExec))
                        .addGap(18, 18, 18)
                        .addGroup(painelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(voltar2)
                            .addComponent(checkFem))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        painelOp1Layout.setVerticalGroup(
            painelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOp1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(labelDescOp1)
                .addGap(33, 33, 33)
                .addGroup(painelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSexo)
                    .addComponent(checkMasc)
                    .addComponent(checkFem))
                .addGap(18, 18, 18)
                .addComponent(checkIdade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(painelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonExec)
                    .addComponent(voltar2))
                .addGap(61, 61, 61))
        );

        //table1.setModel(model);
        //jScrollPane2.setViewportView(table1);

        voltar3.setText("Voltar");
        voltar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltar3ActionPerformed(evt);
            }
        });

        labelTitle.setText("GetFlirting");

        javax.swing.GroupLayout painelOp2Layout = new javax.swing.GroupLayout(painelOp2);
        painelOp2.setLayout(painelOp2Layout);
        painelOp2Layout.setHorizontalGroup(
            painelOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOp2Layout.createSequentialGroup()
                .addGroup(painelOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTitle)
                    .addGroup(painelOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(painelOp2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(painelOp2Layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(voltar3))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        painelOp2Layout.setVerticalGroup(
            painelOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelOp2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelTitle)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(voltar3)
                .addGap(22, 22, 22))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 150, Short.MAX_VALUE)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 150, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 100, Short.MAX_VALUE)
                    .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 100, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>

    private void buttonEntrarActionPerformed(java.awt.event.ActionEvent evt) {
        String token = fieldToken.getText();

        acesso = FacebookAccess.getInstance(token);

        amigos = acesso.getFriendsQuery();
        grafo = new Graph(amigos.size());
        populaGrafo(amigos);
        labelBemVindo.setText(amigos.get(0).getName());
        cards.show(painelPrincipal,"home");
    }

    private void populaGrafo(List<Usuario> amigos) {
		for (int i=0;i<amigos.size();i++) {
			amigos.get(i).setChave(i);
		}
		
		for (int j=0;j<amigos.size();j++) {
			grafo.addEdge(0, amigos.get(j).getChave());
		}
		
	}

	private void buttonMeusFiltrosActionPerformed(java.awt.event.ActionEvent evt) {
        cards.show(painelPrincipal,"op1");
    }

    private void buttonFlirtingFiltrosActionPerformed(java.awt.event.ActionEvent evt) {
        cards.show(painelPrincipal, "op2");
    }

    private void voltar1ActionPerformed(java.awt.event.ActionEvent evt) {
        cards.show(painelPrincipal, "inicio");
    }

    private void buttonExecActionPerformed(java.awt.event.ActionEvent evt) throws MalformedURLException {
    	if (checkMasc.isSelected()){
    		query = acesso.getQueryResult("sex", "male");
    	} else if (checkFem.isSelected()) {
    		query = acesso.getQueryResult("sex", "female");
    	}
    	createTable(query);
        cards.show(painelPrincipal, "op2");
    }

    private void voltar2ActionPerformed(java.awt.event.ActionEvent evt) {
       cards.show(painelPrincipal, "home");
    }

    private void voltar3ActionPerformed(java.awt.event.ActionEvent evt) {
        cards.show(painelPrincipal, "home");
    }

    private void createTable(List<Usuario> query) throws MalformedURLException {
    	String[] nomeColunas = {"Foto", "Nome", "Link" };
    	//Object[][] data = new Object[query.size()][3];
    	/*for (int i=0;i<query.size();i++) {
    		URL url = new URL(query.get(i).getPic());
    		ImageIcon foto = new ImageIcon(url);
    		String nome = query.get(i).getName();
    		String link = query.get(i).getLink();
    		data[i][0] = foto;
			data[i][1] = nome;
			data[i][2] = link;
    		
    	}*/
    	URL a = new URL("logoTipo1.jpg");
    	ImageIcon s = new ImageIcon("logoTipo1.jpg");
    	Object[][] data = {
    			{s.getImage(),"oi","oi"}
    	};
    	model = new DefaultTableModel(data, nomeColunas );
    	table1 = new JTable(model){
    		public Class getColumn(int column) {
    			return getValueAt(0, column).getClass();
    		}
    	};
    	jScrollPane2.setViewportView(table1);
    }
    
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new UI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton buttonEntrar;
    private javax.swing.JButton buttonExec;
    private javax.swing.JButton buttonFlirtingFiltros;
    private javax.swing.JButton buttonMeusFiltros;
    private javax.swing.JCheckBox checkIdade;
    private javax.swing.JCheckBox checkSexo;
    private javax.swing.JTextField fieldToken;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelBemVindo;
    private javax.swing.JLabel labelDescHome;
    private javax.swing.JLabel labelDescOp1;
    private javax.swing.JLabel labelDescToken;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel painelHome;
    private javax.swing.JPanel painelInicio;
    private javax.swing.JPanel painelOp1;
    private javax.swing.JPanel painelOp2;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JCheckBox checkFem;
    private javax.swing.JCheckBox checkMasc;
    private javax.swing.JTable table1;
    private javax.swing.JButton voltar1;
    private javax.swing.JButton voltar2;
    private javax.swing.JButton voltar3;
    // End of variables declaration
}
